### ISSUE TITLE
Use Travis CI's Cassandra service

### ISSUE THREAD

**Issue by BryanSD** [rackerlabs/cdeploy#14]
http://docs.travis-ci.com/user/database-setup/#Cassandra

This would enable us to run the [integration tests](https://github.com/rackerlabs/cdeploy/blob/master/tox.ini#L7) in Travis CI.

**Comment by Kuwagata** [comment]
@BryanSD Got the integration tests to successfully run as part of the travis build in #16.  They seem to get operation timeouts after the first successful run, so I'm not sure what's going on just yet.  This will require some additional investigation and polish.

Most recent docs on docker w/ travis are located [here](http://docs.travis-ci.com/user/docker/).

There's also an annoying, but fixable, iptables issue where the docker chain is missing.

**Comment by BryanSD** [comment]
Addressed in #22.
