### ISSUE TITLE
Timestamp-Based Versions

### ISSUE THREAD

**Issue by bradgignac** [rackerlabs/cdeploy#4]
Incrementing integers as version numbers can be slightly problematic when many develops are working on a project at the same time. I've always though the Ruby on Rails timestamp-based versions are great, because they dramatically reduce the chance of versioning collisions. Would you be open to this style of versioning?

**Comment by BryanSD** [comment]
@bradgignac, can you point me to some documentation about this timestamp-based versioning system? I don't have a history with Ruby on Rails so I'm unfamiliar. I'm happy to consider it after doing a little investigation. Thanks!

**Comment by bradgignac** [comment]
@BryanSD http://edgeguides.rubyonrails.org/active_record_migrations.html#creating-a-standalone-migration

**Comment by BryanSD** [comment]
I took a quick look at this and I *think* it'll actually work with cdeploy as-is. [Currently](https://github.com/rackerlabs/cdeploy/blob/master/cdeploy/migrator.py#L70), the filename is split on underscores and the first portion is converted to an integer. We then simply sort the integers to get the order in which to apply the migration scripts.

If your migration files took the form of `20150317154512_add_table.cql` and `20150317144556_add_column.cql` that'd work, no? Of course that doesn't help if any conflicting CQL statements are contained within two files but you'd have that problem either way.

Maybe it'd be beneficial to add a tip around this to the documentation?

**Comment by BryanSD** [comment]
Closing since this may not be a problem and seems to be abandoned. Happy to reopen if the need arises.
